In [ ]:
import pandas as pd
import googlemaps
import os

In [ ]:
# A chave deve ser configurada em um arquivo .env local
api_key = os.getenv('GOOGLE_API_KEY')
gmaps = googlemaps.Client(key=api_key)

In [67]:
hotel = "Hotel Atlântico Business - R. Sen. Dantas, 25 - Centro, Rio de Janeiro - RJ, 20031-202"
cristo = "Estação Cosme Velho, R. Cosme Velho, 513 - Cosme Velho, Rio de Janeiro - RJ, 22241-091"
jd_botanico = "Jardim Botânico do Rio de Janeiro - R. Jardim Botânico, 1008 - Jardim Botânico, Rio de Janeiro - RJ, 22460-030"
ccbb = "Centro Cultural Banco do Brasil (CCBB) - R. Primeiro de Março, 66 - Centro, Rio de Janeiro - RJ, 20010-000"
museu_amanha = "Museu do Amanhã, Praça Mauá, 1 - Centro, Rio de Janeiro - RJ, 20081-240"
bondinho = "Parque Bondinho Pão de Açúcar, Av. Pasteur, 520 - Urca, Rio de Janeiro - RJ, 22290-240"
aquario = "AquaRio, Praça Muhammad Ali - Via Binário do Porto, s/n - Gamboa, Rio de Janeiro - RJ, 20220-360"
theatro_mun = "Theatro Municipal do Rio de Janeiro, Praça Floriano, S/N - Centro, Rio de Janeiro - RJ, 20031-050"
parque_patins = "Parque dos Patins, Av. Borges de Medeiros, s/n - Lagoa, Rio de Janeiro - RJ, 22470-002"
most_st_bento = "Mosteiro de São Bento, R. Dom Gerardo, 68 - Centro, Rio de Janeiro - RJ, 20090-030"
lapa_st_teresa = "Estação de Bondes de Santa Teresa, R. Lélio Gama, s/n - Centro, Rio de Janeiro - RJ, 20031-080"
forte_copa = "Forte de Copacabana (Museu Histórico do Exército e Forte de Copacabana), Praça Cel. Eugênio Franco, 1, Posto 6 - Copacabana, Rio de Janeiro - RJ, 22070-020"
zoo_rio = "BioParque do Rio, Parque da Quinta da Boa Vista S/N - São Cristóvão, Rio de Janeiro - RJ, 20940-040"
maracana = "Av. Pres. Castelo Branco, S/N - Portão 2 - Maracanã, Rio de Janeiro - RJ, 20271-130"
restaurante = "Praia Shopping - Praia de Botafogo, 400 - 8º andar - Botafogo, Rio de Janeiro - RJ, 22250-910"

In [68]:
pontos = [hotel, cristo, jd_botanico, ccbb, museu_amanha, bondinho, aquario, theatro_mun,
          parque_patins, most_st_bento, lapa_st_teresa, forte_copa, zoo_rio, maracana, restaurante]

In [69]:
nomes_pontos = {
    hotel: "Hotel",
    cristo: "Cristo Redentor",
    jd_botanico: "Jardim Botânico",
    ccbb: "CCBB",
    museu_amanha: "Museu do Amanhã",
    bondinho: "Pão de Açúcar",
    aquario: "AquaRio",
    theatro_mun: "Theatro Municipal",
    parque_patins: "Parque dos Patins",
    most_st_bento: "Mosteiro de São Bento",
    lapa_st_teresa: "Santa Teresa",
    forte_copa: "Forte de Copacabana",
    zoo_rio: "BioParque do Rio",
    maracana: "Maracanã",
    restaurante: "Restaurante Spesso"
}

In [70]:
print(pontos)
print(len(pontos))  # Verifica o número de pontos na lista

['Hotel Atlântico Business - R. Sen. Dantas, 25 - Centro, Rio de Janeiro - RJ, 20031-202', 'Estação Cosme Velho, R. Cosme Velho, 513 - Cosme Velho, Rio de Janeiro - RJ, 22241-091', 'Jardim Botânico do Rio de Janeiro - R. Jardim Botânico, 1008 - Jardim Botânico, Rio de Janeiro - RJ, 22460-030', 'Centro Cultural Banco do Brasil (CCBB) - R. Primeiro de Março, 66 - Centro, Rio de Janeiro - RJ, 20010-000', 'Museu do Amanhã, Praça Mauá, 1 - Centro, Rio de Janeiro - RJ, 20081-240', 'Parque Bondinho Pão de Açúcar, Av. Pasteur, 520 - Urca, Rio de Janeiro - RJ, 22290-240', 'AquaRio, Praça Muhammad Ali - Via Binário do Porto, s/n - Gamboa, Rio de Janeiro - RJ, 20220-360', 'Theatro Municipal do Rio de Janeiro, Praça Floriano, S/N - Centro, Rio de Janeiro - RJ, 20031-050', 'Parque dos Patins, Av. Borges de Medeiros, s/n - Lagoa, Rio de Janeiro - RJ, 22470-002', 'Mosteiro de São Bento, R. Dom Gerardo, 68 - Centro, Rio de Janeiro - RJ, 20090-030', 'Estação de Bondes de Santa Teresa, R. Lélio Gama, s/n - Centro, Rio de Janeiro - RJ, 20031-080', 'Forte de Copacabana (Museu Histórico do Exército e Forte de Copacabana), Praça Cel. Eugênio Franco, 1, Posto 6 - Copacabana, Rio de Janeiro - RJ, 22070-020', 'BioParque do Rio, Parque da Quinta da Boa Vista S/N - São Cristóvão, Rio de Janeiro - RJ, 20940-040', 'Av. Pres. Castelo Branco, S/N - Portão 2 - Maracanã, Rio de Janeiro - RJ, 20271-130', 'Praia Shopping - Praia de Botafogo, 400 - 8º andar - Botafogo, Rio de Janeiro - RJ, 22250-910']
15

In [71]:
# Definindo um dicionário para armazenar as rotas com os nomes dos pontos
rotas_dict = {}

# Iterando sobre os pontos para criar as rotas
for i in range(len(pontos)):
    for j in range(len(pontos)):
        if i != j:
            origem = pontos[i]
            destino = pontos[j]
            
            # Usando os nomes dos pontos para facilitar a visualização
            nome_origem = nomes_pontos[origem]
            nome_destino = nomes_pontos[destino]
            
            # Consultando a API para obter os resultados de direção
            results = gmaps.directions(origin=origem, destination=destino, mode='walking')

            # Pegar o tempo total (em segundos) da primeira rota
            duration_seconds = results[0]['legs'][0]['duration']['value']

            # Converter para minutos
            duration_minutes = duration_seconds / 60
            if duration_minutes > 30:
                results = gmaps.directions(origin=origem, destination=destino, mode='transit', traffic_model='pessimistic')

            
            # Removendo as chaves indesejadas do resultado completo
            for route in results:
                # Remover chaves indesejadas no nível superior (não dentro de 'legs')
                for key in ['bounds','copyrights', 'overview_polyline', 'summary', 'warnings', 'waypoint_order']:
                    if key in route:
                        del route[key]

            # Salvando os resultados no dicionário com os nomes dos pontos como chave
            rotas_dict[(nome_origem, nome_destino)] = results

In [72]:
# Exibindo o dicionário de rotas
for (origem, destino), rota in rotas_dict.items():
    print(f"Rota de {origem} para {destino}:")
    print(rota)  # ou qualquer outra informação que você deseje exibir

Rota de Hotel para Cristo Redentor:
[{'legs': [{'arrival_time': {'text': '1:58\u202fAM', 'time_zone': 'America/Sao_Paulo', 'value': 1734497919}, 'departure_time': {'text': '12:39\u202fAM', 'time_zone': 'America/Sao_Paulo', 'value': 1734493178}, 'distance': {'text': '5.4 km', 'value': 5370}, 'duration': {'text': '1 hour 19 mins', 'value': 4741}, 'end_address': 'R. Cosme Velho, 513 - Cosme Velho, Rio de Janeiro - RJ, 22241-091, Brazil', 'end_location': {'lat': -22.9412686, 'lng': -43.198775}, 'start_address': 'R. Sen. Dantas, 25 - Centro, Rio de Janeiro - RJ, 20031-202, Brazil', 'start_location': {'lat': -22.9114028, 'lng': -43.1768638}, 'steps': [{'distance': {'text': '0.4 km', 'value': 385}, 'duration': {'text': '5 mins', 'value': 312}, 'end_location': {'lat': -22.9124174, 'lng': -43.1743235}, 'html_instructions': 'Walk to Rio Branco', 'polyline': {'points': 'f{yjCj~ofGd@UFENIlAm@LIOUGKUk@Sa@Kw@CI?K?E@E@GBER[FGBArA_@ZGACAIAK@U?M@GBCDECGBE[Y'}, 'start_location': {'lat': -22.9114028, 'lng': -43.1768638}, 'steps': [{'distance': {'text': '0.1 km', 'value': 102}, 'duration': {'text': '1 min', 'value': 81}, 'end_location': {'lat': -22.9121662, 'lng': -43.17639459999999}, 'html_instructions': 'Head <b>southeast</b> on <b>R. Sen. Dantas</b> toward <b>R. Emb. Régis de Oliveira</b>', 'polyline': {'points': 'f{yjCj~ofGd@UFENIlAm@LI'}, 'start_location': {'lat': -22.9114028, 'lng': -43.1768638}, 'travel_mode': 'WALKING'}, {'distance': {'text': '61 m', 'value': 61}, 'duration': {'text': '1 min', 'value': 51}, 'end_location': {'lat': -22.9117762, 'lng': -43.1755544}, 'html_instructions': 'Turn <b>left</b> onto <b>R. do Passeio</b>', 'maneuver': 'turn-left', 'polyline': {'points': '``zjCl{ofGOUGKUk@Sa@Kw@'}, 'start_location': {'lat': -22.9121662, 'lng': -43.17639459999999}, 'travel_mode': 'WALKING'}, {'distance': {'text': '0.1 km', 'value': 143}, 'duration': {'text': '2 mins', 'value': 115}, 'end_location': {'lat': -22.9125162, 'lng': -43.17492379999999}, 'html_instructions': 'Slight <b>right</b> onto <b>Av. Rio Branco</b>', 'maneuver': 'turn-slight-right', 'polyline': {'points': 'r}yjCdvofGCI?K?E@E@GBER[FGBArA_@ZG'}, 'start_location': {'lat': -22.9117762, 'lng': -43.1755544}, 'travel_mode': 'WALKING'}, {'distance': {'text': '58 m', 'value': 58}, 'duration': {'text': '1 min', 'value': 48}, 'end_location': {'lat': -22.912564, 'lng': -43.1744513}, 'html_instructions': 'Turn <b>left</b> toward <b>Av. Pres. Wilson</b>', 'maneuver': 'turn-left', 'polyline': {'points': 'fbzjCfrofGACAIAK@U?M@GBCDECGBE'}, 'start_location': {'lat': -22.9125162, 'lng': -43.17492379999999}, 'travel_mode': 'WALKING'}, {'distance': {'text': '21 m', 'value': 21}, 'duration': {'text': '1 min', 'value': 17}, 'end_location': {'lat': -22.9124174, 'lng': -43.1743235}, 'html_instructions': 'Turn <b>left</b> onto <b>Av. Pres. Wilson</b>', 'maneuver': 'turn-left', 'polyline': {'points': 'nbzjChoofG[Y'}, 'start_location': {'lat': -22.912564, 'lng': -43.1744513}, 'travel_mode': 'WALKING'}], 'travel_mode': 'WALKING'}, {'distance': {'text': '4.8 km', 'value': 4823}, 'duration': {'text': '11 mins', 'value': 666}, 'end_location': {'lat': -22.9404, 'lng': -43.19802}, 'html_instructions': 'Bus towards Cosme Velho', 'polyline': {'points': 'razjCnnofGDG\\XZTh@^LJWRn@j@VTJHPPz@j@pAt@NH\\XPNLFZJRFHBH@NBfAJjBNj@DtDXh@D`@Dz@Fn@Fb@DJ?N@@?J?D?JAF?HADAJADAJCHCJEJEJEDEFELKHI?ADEz@gARRPNRNt@p@LJB@HDHBJDPDPBNBB?D@LBR@p@L`@HXDLBdC`@L@p@Ht@H@?B@hBLfAJDDFBFBFDFDBBDDXj@^x@HNnAjC\\t@n@rALXHCJCZGb@GZGLE\\EVC\\Cb@Av@?n@?X?r@A^?\\?T?B?d@?z@?j@?b@?HAZ?F?b@AF?F@RBVBF@lBRPBH?D?HAXKTGNEh@Oh@OVz@t@SDAD?LCHAH?V?HTNr@d@rBJ`@Ld@TbAp@dCBNJf@?@H^BHl@fCDPVdADR@BDPBJFLVl@Nf@JVHFBDDDDJ@BL`@DRATAb@A`@?d@@JDVBXTn@FPHPJTFHR`@\\r@j@dADHLVR^Zj@R`@JP\\r@DJNXP\\BF\\r@DLLTFLLX?@LTDHDHHLBDBDFFHFJJNNTR\\Zb@^PJNDJBH@LBHBp@HH@z@JNFb@FXBB@D@F@B@@?FBH@BBB@B@DBBBDBDDHHDFFHDFDHFNBD@DBHBF?F@D?@@@?F?FBb@B`@Bt@Bb@@LDbA@R@P@X@N@L?D?BBR?HBJ@N@DFd@@D?B?BBd@ANAXAJAFADEJEPKZMd@[`ACFAD?@CFEP?@CZ?H@\\FVJRBBRPlCr@l@PPBN@TD\\FFD@BDDB@BDHJJLJNLRDDLPRZNP@BDHBD@DDDDH@B@D@L@L?H?B?DCNAPEZETERMA'}, 'start_location': {'lat': -22.91242, 'lng': -43.17432}, 'transit_details': {'arrival_stop': {'location': {'lat': -22.9404, 'lng': -43.19802}, 'name': 'Santuário São Judas Tadeu'}, 'arrival_time': {'text': '1:55\u202fAM', 'time_zone': 'America/Sao_Paulo', 'value': 1734497756}, 'departure_stop': {'location': {'lat': -22.91242, 'lng': -43.17432}, 'name': 'Rio Branco'}, 'departure_time': {'text': '1:44\u202fAM', 'time_zone': 'America/Sao_Paulo', 'value': 1734497090}, 'headsign': 'Cosme Velho', 'headway': 3600, 'line': {'agencies': [{'name': 'Prefeitura do Rio - Intersul', 'phone': '011 55 800 886 1000', 'url': 'http://www.rioonibus.com/'}], 'color': '#daaa00', 'name': 'Grajaú - Cosme Velho', 'short_name': 'SN422', 'text_color': '#000000', 'vehicle': {'icon': '//maps.gstatic.com/mapfiles/transit/iw2/6/bus2.png', 'name': 'Bus', 'type': 'BUS'}}, 'num_stops': 18, 'trip_short_name': 'SN422'}, 'travel_mode': 'TRANSIT'}, {'distance': {'text': '0.2 km', 'value': 162}, 'duration': {'text': '3 mins', 'value': 163}, 'end_location': {'lat': -22.9412686, 'lng': -43.198775}, 'html_instructions': 'Walk to R. Cosme Velho, 513 - Cosme Velho, Rio de Janeiro - RJ, 22241-091, Brazil', 'polyline': {'points': 'lp_kCrbtfGALCTGVCPB?THEPPBVFF@XDH@@@NBNBLBf@H'}, 'start_location': {'lat': -22.9403934, 'lng': -43.1980235}, 'steps': [{'distance': {'text': '56 m', 'value': 56}, 'duration': {'text': '1 min', 'value': 63}, 'end_location': {'lat': -22.940404, 'lng': -43.1985458}, 'html_instructions': 'Head <b>west</b> on <b>R. Cosme Velho</b> toward <b>Prç. São Judas Tadeu</b>', 'polyline': {'points': 'lp_kCrbtfGALCTGVCPB?THEP'}, 'start_location': {'lat': -22.9403934, 'lng': -43.1980235}, 'travel_mode': 'WALKING'}, {'distance': {'text': '0.1 km', 'value': 106}, 'duration': {'text': '2 mins', 'value': 100}, 'end_location': {'lat': -22.9412686, 'lng': -43.198775}, 'html_instructions': 'Turn <b>left</b> onto <b>R. Smith de Vasconcelos</b><div style="font-size:0.9em">Destination will be on the right</div>', 'maneuver': 'turn-left', 'polyline': {'points': 'np_kC|etfGPBVFF@XDH@@@NBNBLBf@H'}, 'start_location': {'lat': -22.940404, 'lng': -43.1985458}, 'travel_mode': 'WALKING'}], 'travel_mode': 'WALKING'}], 'traffic_speed_entry': [], 'via_waypoint': []}]}]
Rota de Hotel para Jardim Botânico:
[{'legs': [{'arrival_time': {'text': '1:27\u202fAM', 'time_zone': 'America/Sao_Paulo', 'value': 1734496063}, 'departure_time': {'text': '12:39\u202fAM', 'time_zone': 'America/Sao_Paulo', 'value': 1734493178}, 'distance': {'text': '10.6 km', 'value': 10585}, 'duration': {'text': '48 mins', 'value': 2885}, 'end_address': 'Botanical Garden of Rio de Janeiro - R. Jardim Botânico, 1008 - Jardim Botânico, Rio de Janeiro - RJ, 22460-030, Brazil', 'end_location': {'lat': -22.9705513, 'lng': -43.2235178}, 'start_address': 'R. Sen. Dantas, 25 - Centro, Rio de Janeiro - RJ, 20031-202, Brazil', 'start_location': {'lat': -22.9114028, 'lng': -43.1768638}, 'steps': [{'distance': {'text': '0.4 km', 'value': 385}, 'duration': {'text': '5 mins', 'value': 312}, 'end_location': {'lat': -22.9124174, 'lng': -43.1743235}, 'html_instructions': 'Walk to Rio Branco', 'polyline': {'points': 'f{yjCj~ofGd@UFENIlAm@LIOUGKUk@Sa@Kw@CI?K?E@E@GBER[FGBArA_@ZGACAIAK@U?M@GBCDECGBE[Y'}, 'start_location': {'lat': -22.9114028, 'lng': -43.1768638}, 'steps': [{'distance': {'text': '0.1 km', 'value': 102}, 'duration': {'text': '1 min', 'value': 81}, 'end_location': {'lat': -22.9121662, 'lng': -43.17639459999999}, 'html_instructions': 'Head <b>southeast</b> on <b>R. Sen. Dantas</b> toward <b>R. Emb. Régis de Oliveira</b>', 'polyline': {'points': 'f{yjCj~ofGd@UFENIlAm@LI'}, 'start_location': {'lat': -22.9114028, 'lng': -43.1768638}, 'travel_mode': 'WALKING'}, {'distance': {'text': '61 m', 'value': 61}, 'duration': {'text': '1 min', 'value': 51}, 'end_location': {'lat': -22.9117762, 'lng': -43.1755544}, 'html_instructions': 'Turn <b>left</b> onto <b>R. do Passeio</b>', 'maneuver': 'turn-left', 'polyline': {'points': '``zjCl{ofGOUGKUk@Sa@Kw@'}, 'start_location': {'lat': -22.9121662, 'lng': -43.17639459999999}, 'travel_mode': 'WALKING'}, {'distance': {'text': '0.1 km', 'value': 143}, 'duration': {'text': '2 mins', 'value': 115}, 'end_location': {'lat': -22.9125162, 'lng': -43.17492379999999}, 'html_instructions': 'Slight <b>right</b> onto <b>Av. Rio Branco</b>', 'maneuver': 'turn-slight-right', 'polyline': {'points': 'r}yjCdvofGCI?K?E@E@GBER[FGBArA_@ZG'}, 'start_location': {'lat': -22.9117762, 'lng': -43.1755544}, 'travel_mode': 'WALKING'}, {'distance': {'text': '58 m', 'value': 58}, 'duration': {'text': '1 min', 'value': 48}, 'end_location': {'lat': -22.912564, 'lng': -43.1744513}, 'html_instructions': 'Turn <b>left</b> toward <b>Av. Pres. Wilson</b>', 'maneuver': 'turn-left', 'polyline': {'points': 'fbzjCfrofGACAIAK@U?M@GBCDECGBE'}, 'start_location': {'lat': -22.9125162, 'lng': -43.17492379999999}, 'travel_mode': 'WALKING'}, {'distance': {'text': '21 m', 'value': 21}, 'duration': {'text': '1 min', 'value': 17}, 'end_location': {'lat': -22.9124174, 'lng': -43.1743235}, 'html_instructions': 'Turn <b>left</b> onto <b>Av. Pres. Wilson</b>', 'maneuver': 'turn-left', 'polyline': {'points': 'nbzjChoofG[Y'}, 'start_location': {'lat': -22.912564, 'lng': -43.1744513}, 'travel_mode': 'WALKING'}], 'travel_mode': 'WALKING'}, {'distance': {'text': '10.1 km', 'value': 10112}, 'duration': {'text': '22 mins', 'value': 1297}, 'end_location': {'lat': -22.97101, 'lng': -43.22336}, 'html_instructions': 'Bus towards Terminal Alvorada', 'polyline': {'points': 'razjCnnofGDG\\XZTh@^LJb@\\@@VT^\\PNFFLHLHNH\\Tv@d@HFNJNJZTD@FBRDNBB@F@HBN@B?|BPz@H`BLh@Br@Fh@F`@BbBLt@FJ@H?L?F?FAHAFALCJCJC@AJEFELGFGFEBCNSNSb@k@t@cAr@cAJO`@g@HMFGHKJILKBCBEJM^OJC`AuA^g@f@q@j@w@f@k@PQLKXS^SVKFEHCFCHCRGJCHAb@Ij@ED?VAX?r@Bn@HnAV~@R`Dp@zDx@`B\\jB`@p@LJ@p@PpBb@D@`@HbB\\b@HJBD?H@H@VB`@Bf@DT@v@DdADT@nCNp@DjBJpAF\\?D?h@A`@AbAEn@GNAbCUj@Gn@EXErBQn@GbAIh@GzBULATCr@GB?z@Ib@EBARANCR@L@NLDBFFHJX\\`AlALRZ\\HHTZj@r@r@|@RXPVj@t@^d@^d@HHb@j@@Bb@l@CDCDCJGNGROd@M`@ELADADAV@JBRBVDZ@XBVDX?@H^FPDLPf@LVHPHRTh@HPRb@T`@?@NTHJDFJN`@f@DFDHHJHLLPPNFJFFHH@@LJLJJHNJLHn@`@zAr@h@RNFv@Z`@Jf@LXFj@J`@FRD`@FXBtALL@J?T@\\@R?`@Ar@?hBKTARAd@GVCj@Ib@GJ?R?FAXGJ?D?F@FBPFDBHJBD@BLJAZB\\D`ABr@@H@RBd@?RD`@D`@BZ?R@d@@v@F`BBt@@RBlABn@@h@BbAADDhAAF@fA?d@@T?b@?B@rA@J@TD^D\\XxBRxAF`@Hh@BN@H@DNz@TvAVpABN@D@HH^Lx@Lt@BNL^HRPd@^z@N^Xr@J\\DJLZTh@JTHPBDLZFNFLXd@FJFHLRZf@JLXd@V^LNHJLJNLHDRJ@?DBf@Th@TZJf@RVJr@ZjAd@PHZPBBPJp@b@RLTLHFRHNHNFHBD@DBHDh@VFBJDVJDB`@NZLXJj@TRNnAv@d@VJHFB?@NHPLl@^l@^`Ah@FDFDTPLPHJDH?@f@vAN^@@@Bb@fAPb@\\~@N\\DJ\\~@^dAFTJX@JDTD`@B`@Bf@@n@@L?F@d@?LBd@@B@BBBBBDB@N@^BNBd@?T@HTrDBn@Dr@Dj@?BDd@HbBL`BH~@HhBHjABXBd@@JJpBJfAH~AJtBHlBDr@Dz@FvA@VBt@@\\BX@HBZF`@@DDTBPBJHVHZN`@JRFNNVLR@BLNHLPTNPRRb@^r@n@b@b@JHl@h@NNPPDD\\Z`Az@h@h@BBBBDBHJHFv@n@j@j@DDDD\\ZPNTR^XtAhAJHlAx@\\TJHNLp@f@lAz@|DfDvDvCr@f@FFpD|CVR\\XtA`AVPMR'}, 'start_location': {'lat': -22.91242, 'lng': -43.17432}, 'transit_details': {'arrival_stop': {'location': {'lat': -22.97101, 'lng': -43.22336}, 'name': 'Jóquei Clube'}, 'arrival_time': {'text': '1:26\u202fAM', 'time_zone': 'America/Sao_Paulo', 'value': 1734495987}, 'departure_stop': {'location': {'lat': -22.91242, 'lng': -43.17432}, 'name': 'Rio Branco'}, 'departure_time': {'text': '1:04\u202fAM', 'time_zone': 'America/Sao_Paulo', 'value': 1734494690}, 'headsign': 'Terminal Alvorada', 'headway': 1200, 'line': {'agencies': [{'name': 'Prefeitura do Rio - Transcarioca', 'phone': '011 55 800 886 1000', 'url': 'http://www.rioonibus.com/'}], 'color': '#279ee8', 'name': 'Terminal Alvorada - Terminal Gentileza', 'short_name': 'SN309', 'text_color': '#ffffff', 'vehicle': {'icon': '//maps.gstatic.com/mapfiles/transit/iw2/6/bus2.png', 'name': 'Bus', 'type': 'BUS'}}, 'num_stops': 28, 'trip_short_name': 'SN309'}, 'travel_mode': 'TRANSIT'}, {'distance': {'text': '88 m', 'value': 88}, 'duration': {'text': '1 min', 'value': 76}, 'end_location': {'lat': -22.9705513, 'lng': -43.2235178}, 'html_instructions': 'Walk to Botanical Garden of Rio de Janeiro - R. Jardim Botânico, 1008 - Jardim Botânico, Rio de Janeiro - RJ, 22460-030, Brazil', 'polyline': {'points': '|oekCx`yfGMIADADEN?FW?E@GDKPGEEECAA?A?'}, 'start_location': {'lat': -22.9710293, 'lng': -43.2233306}, 'steps': [{'distance': {'text': '16 m', 'value': 16}, 'duration': {'text': '1 min', 'value': 13}, 'end_location': {'lat': -22.9709613, 'lng': -43.2232779}, 'html_instructions': 'Head <b>northeast</b> on <b>R. Jardim Botânico</b>', 'polyline': {'points': '|oekCx`yfGMI'}, 'start_location': {'lat': -22.9710293, 'lng': -43.2233306}, 'travel_mode': 'WALKING'}, {'distance': {'text': '30 m', 'value': 30}, 'duration': {'text': '1 min', 'value': 26}, 'end_location': {'lat': -22.9709052, 'lng': -43.2234556}, 'html_instructions': 'Turn <b>left</b> to stay on <b>R. Jardim Botânico</b><div style="font-size:0.9em">Restricted usage road</div>', 'maneuver': 'turn-left', 'polyline': {'points': 'noekCn`yfGADADEN?F'}, 'start_location': {'lat': -22.9709613, 'lng': -43.2232779}, 'travel_mode': 'WALKING'}, {'distance': {'text': '28 m', 'value': 28}, 'duration': {'text': '1 min', 'value': 25}, 'end_location': {'lat': -22.9706573, 'lng': -43.2235873}, 'html_instructions': 'Turn <b>right</b><div style="font-size:0.9em">Restricted usage road</div>', 'maneuver': 'turn-right', 'polyline': {'points': 'doekCrayfGW?E@GDKP'}, 'start_location': {'lat': -22.9709052, 'lng': -43.2234556}, 'travel_mode': 'WALKING'}, {'distance': {'text': '5 m', 'value': 5}, 'duration': {'text': '1 min', 'value': 4}, 'end_location': {'lat': -22.9706235, 'lng': -43.2235591}, 'html_instructions': 'Turn <b>right</b><div style="font-size:0.9em">Restricted usage road</div>', 'maneuver': 'turn-right', 'polyline': {'points': 'rmekClbyfGGE'}, 'start_location': {'lat': -22.9706573, 'lng': -43.2235873}, 'travel_mode': 'WALKING'}, {'distance': {'text': '9 m', 'value': 9}, 'duration': {'text': '1 min', 'value': 8}, 'end_location': {'lat': -22.9705513, 'lng': -43.2235178}, 'html_instructions': 'Slight <b>left</b><div style="font-size:0.9em">Restricted usage road</div><div style="font-size:0.9em">Destination will be on the right</div>', 'maneuver': 'turn-slight-left', 'polyline': {'points': 'jmekCfbyfGEECAA?A?'}, 'start_location': {'lat': -22.9706235, 'lng': -43.2235591}, 'travel_mode': 'WALKING'}], 'travel_mode': 'WALKING'}], 'traffic_speed_entry': [], 'via_waypoint': []}]}]
Rota de Hotel para CCBB:
[{'legs': [{'distance': {'text': '1.4 km', 'value': 1403}, 'duration': {'text': '20 mins', 'value': 1181}, 'end_address': 'R. Primeiro de Março, 66 - Centro, Rio de Janeiro - RJ, 20010-000, Brazil', 'end_location': {'lat': -22.9011498, 'lng': -43.1764896}, 'start_address': 'R. Sen. Dantas, 25 - Centro, Rio de Janeiro - RJ, 20031-202, Brazil', 'start_location': {'lat': -22.9114028, 'lng': -43.1768638}, 'steps': [{'distance': {'text': '0.1 km', 'value': 130}, 'duration': {'text': '2 mins', 'value': 107}, 'end_location': {'lat': -22.9105123, 'lng': -43.1773679}, 'html_instructions': 'Head <b>northwest</b> on <b>R. Sen. Dantas</b> toward <b>R. Francisco Serrador</b>', 'polyline': {'points': 'f{yjCj~ofGA@IBGBsAn@SLMJIF[LAC'}, 'start_location': {'lat': -22.9114028, 'lng': -43.1768638}, 'travel_mode': 'WALKING'}, {'distance': {'text': '0.2 km', 'value': 176}, 'duration': {'text': '2 mins', 'value': 140}, 'end_location': {'lat': -22.9093286, 'lng': -43.1759054}, 'html_instructions': 'Turn <b>right</b> onto <b>R. Evaristo da Veiga</b>', 'maneuver': 'turn-right', 'polyline': {'points': 'tuyjCpapfGISQHk@g@IIYWMOMMWa@AMAKg@eAEGSk@EB'}, 'start_location': {'lat': -22.9105123, 'lng': -43.1773679}, 'travel_mode': 'WALKING'}, {'distance': {'text': '0.7 km', 'value': 736}, 'duration': {'text': '11 mins', 'value': 631}, 'end_location': {'lat': -22.9031205, 'lng': -43.1783788}, 'html_instructions': 'Turn <b>left</b> onto <b>Av. Rio Branco</b>', 'maneuver': 'turn-left', 'polyline': {'points': 'hnyjClxofGSFE@N`@IBA?ODE@C@E@E@U@E@C@E?UHe@Lc@JEBKFIDE@MDGq@C@k@RLj@WHKBI?O@C@KBGBy@RSF_Bd@E@UHDk@EB[J?FQDi@NQDg@NCGC@QFLVc@Fq@RIBc@PMCQNmFvAGD[Js@PKDI@'}, 'start_location': {'lat': -22.9093286, 'lng': -43.1759054}, 'travel_mode': 'WALKING'}, {'distance': {'text': '0.3 km', 'value': 265}, 'duration': {'text': '4 mins', 'value': 215}, 'end_location': {'lat': -22.9019511, 'lng': -43.1760374}, 'html_instructions': 'Turn <b>right</b> onto <b>R. do Rosário</b>', 'maneuver': 'turn-right', 'polyline': {'points': 'ngxjCzgpfGa@eAEIw@qBCI_@{@Q_@GMCGy@sBBACCIWCC'}, 'start_location': {'lat': -22.9031205, 'lng': -43.1783788}, 'travel_mode': 'WALKING'}, {'distance': {'text': '0.1 km', 'value': 96}, 'duration': {'text': '1 min', 'value': 88}, 'end_location': {'lat': -22.9011498, 'lng': -43.1764896}, 'html_instructions': 'Turn <b>left</b> onto <b>R. Primeiro de Março</b><div style="font-size:0.9em">Destination will be on the right</div>', 'maneuver': 'turn-left', 'polyline': {'points': 'd`xjCfyofGEFOHMFOHa@PMDUHSJQF'}, 'start_location': {'lat': -22.9019511, 'lng': -43.1760374}, 'travel_mode': 'WALKING'}], 'traffic_speed_entry': [], 'via_waypoint': []}]}]
Rota de Hotel para Museu do Amanhã:

In [73]:
# Criar uma lista para armazenar os dados extraídos
data = []

# Iterar sobre o dicionário de rotas
for (origem, destino), rotas in rotas_dict.items():
    for rota in rotas:
        # Inicializando as variáveis para cada rota
        total_distance_km = 0
        total_distance_m = 0
        total_duration_min = 0
        fare_currency = None
        fare_value = None
        step_modes = []

        # Verificar se o fare está presente
        if 'fare' in rota:
            fare_currency = rota['fare'].get('currency', None)
            fare_value = rota['fare'].get('text', None)

        # Iterar sobre as "legs" da rota
        for leg in rota.get('legs', []):
            total_distance_km += leg.get('distance', {}).get('value', 0) / 1000  # Convertendo metros para km
            total_distance_m += leg.get('distance', {}).get('value', 0)  # Metros
            total_duration_min += leg.get('duration', {}).get('value', 0) / 60  # Convertendo segundos para minutos

            # Capturar os modos de transporte de cada passo
            for step in leg.get('steps', []):
                travel_mode = step.get('travel_mode', 'UNKNOWN')

                # Identificar e formatar a descrição do modo de transporte
                if 'Bus towards' in step.get('html_instructions', ''):
                    step_modes.append('Bus')
                elif 'Subway towards' in step.get('html_instructions', ''):
                    step_modes.append('Subway')
                elif travel_mode == 'WALKING':
                    step_modes.append('Walking')
                elif travel_mode == 'BICYCLING':
                    step_modes.append('Bicycle')
                elif travel_mode == 'DRIVING':
                    step_modes.append('Driving')
                else:
                    step_modes.append(travel_mode)  # Caso algum outro modo seja identificado

        # Armazenar os dados na lista
        data.append({
            'origem': origem,
            'destino': destino,
            'total_distance_km': total_distance_km,
            'total_distance_m': total_distance_m,
            'total_duration_min': total_duration_min,
            'fare_currency': fare_currency,
            'fare_value': fare_value,
            'step_mode': ' | '.join(step_modes)  # Concatena os modos de transporte por |
        })

# Criar o DataFrame com os dados extraídos
df_rotas = pd.DataFrame(data)

In [74]:
# Exibir o DataFrame resultante
df_rotas

,origem,destino,total_distance_km,total_distance_m,total_duration_min,fare_currency,fare_value,step_mode
0,Hotel,Cristo Redentor,5.370,5370,79.016667,None,None,Walking | Bus | Walking
1,Hotel,Jardim Botânico,10.585,10585,48.083333,None,None,Walking | Bus | Walking
2,Hotel,CCBB,1.403,1403,19.683333,None,None,Walking | Walking | Walking | Walking | Walking
3,Hotel,Museu do Amanhã,2.224,2224,31.466667,None,None,Walking
4,Hotel,Pão de Açúcar,7.487,7487,47.500000,BRL,R$7.50,Walking | Subway | Walking
...,...,...,...,...,...,...,...,...
205,Restaurante Spesso,Mosteiro de São Bento,8.371,8371,45.333333,None,None,Walking | Bus | Walking
206,Restaurante Spesso,Santa Teresa,6.832,6832,44.166667,None,None,Walking | Bus | Walking
207,Restaurante Spesso,Forte de Copacabana,6.387,6387,56.616667,None,None,Walking | Bus | Walking
208,Restaurante Spesso,BioParque do Rio,13.185,13185,60.666667,None,None,Walking | Bus | Walking | Bus | Walking
209,Restaurante Spesso,Maracanã,12.942,12942,86.433333,None,None,Walking | Bus | Walking

In [75]:
# Contar a ocorrência de cada modo de transporte em 'step_mode' para cada linha
df_rotas['walking'] = df_rotas['step_mode'].str.count('Walking')
df_rotas['bus'] = df_rotas['step_mode'].str.count('Bus')
df_rotas['subway'] = df_rotas['step_mode'].str.count('Subway')

df_rotas

,origem,destino,total_distance_km,total_distance_m,total_duration_min,fare_currency,fare_value,step_mode,walking,bus,subway
0,Hotel,Cristo Redentor,5.370,5370,79.016667,None,None,Walking | Bus | Walking,2,1,0
1,Hotel,Jardim Botânico,10.585,10585,48.083333,None,None,Walking | Bus | Walking,2,1,0
2,Hotel,CCBB,1.403,1403,19.683333,None,None,Walking | Walking | Walking | Walking | Walking,5,0,0
3,Hotel,Museu do Amanhã,2.224,2224,31.466667,None,None,Walking,1,0,0
4,Hotel,Pão de Açúcar,7.487,7487,47.500000,BRL,R$7.50,Walking | Subway | Walking,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...
205,Restaurante Spesso,Mosteiro de São Bento,8.371,8371,45.333333,None,None,Walking | Bus | Walking,2,1,0
206,Restaurante Spesso,Santa Teresa,6.832,6832,44.166667,None,None,Walking | Bus | Walking,2,1,0
207,Restaurante Spesso,Forte de Copacabana,6.387,6387,56.616667,None,None,Walking | Bus | Walking,2,1,0
208,Restaurante Spesso,BioParque do Rio,13.185,13185,60.666667,None,None,Walking | Bus | Walking | Bus | Walking,3,2,0
209,Restaurante Spesso,Maracanã,12.942,12942,86.433333,None,None,Walking | Bus | Walking,2,1,0

In [76]:
# Selecionar as colunas desejadas
df_filter = df_rotas[['origem', 'destino', 'total_duration_min', 'walking', 'bus', 'subway']]

df_filter = df_filter.copy()
df_filter['custo'] = (df_filter['bus'] * 4.3) + (df_filter['subway'] * 7.5)
df_filter

,origem,destino,total_duration_min,walking,bus,subway,custo
0,Hotel,Cristo Redentor,79.016667,2,1,0,4.3
1,Hotel,Jardim Botânico,48.083333,2,1,0,4.3
2,Hotel,CCBB,19.683333,5,0,0,0.0
3,Hotel,Museu do Amanhã,31.466667,1,0,0,0.0
4,Hotel,Pão de Açúcar,47.500000,2,0,1,7.5
...,...,...,...,...,...,...,...
205,Restaurante Spesso,Mosteiro de São Bento,45.333333,2,1,0,4.3
206,Restaurante Spesso,Santa Teresa,44.166667,2,1,0,4.3
207,Restaurante Spesso,Forte de Copacabana,56.616667,2,1,0,4.3
208,Restaurante Spesso,BioParque do Rio,60.666667,3,2,0,8.6
209,Restaurante Spesso,Maracanã,86.433333,2,1,0,4.3

In [81]:
# Contar as ocorrências de cada origem
contagem_origens = df_filter['origem'].value_counts()

# Filtrar origens com menos de 13 linhas
origens_com_problema = contagem_origens[contagem_origens <= len(pontos) - 1]

# Exibir o resultado
print(origens_com_problema)

origem
Hotel                    14
Cristo Redentor          14
Jardim Botânico          14
CCBB                     14
Museu do Amanhã          14
Pão de Açúcar            14
AquaRio                  14
Theatro Municipal        14
Parque dos Patins        14
Mosteiro de São Bento    14
Santa Teresa             14
Forte de Copacabana      14
BioParque do Rio         14
Maracanã                 14
Restaurante Spesso       14
Name: count, dtype: int64

In [82]:
df_caminhos = df_filter.copy()

In [83]:
df_caminhos

,origem,destino,total_duration_min,walking,bus,subway,custo
0,Hotel,Cristo Redentor,79.016667,2,1,0,4.3
1,Hotel,Jardim Botânico,48.083333,2,1,0,4.3
2,Hotel,CCBB,19.683333,5,0,0,0.0
3,Hotel,Museu do Amanhã,31.466667,1,0,0,0.0
4,Hotel,Pão de Açúcar,47.500000,2,0,1,7.5
...,...,...,...,...,...,...,...
205,Restaurante Spesso,Mosteiro de São Bento,45.333333,2,1,0,4.3
206,Restaurante Spesso,Santa Teresa,44.166667,2,1,0,4.3
207,Restaurante Spesso,Forte de Copacabana,56.616667,2,1,0,4.3
208,Restaurante Spesso,BioParque do Rio,60.666667,3,2,0,8.6
209,Restaurante Spesso,Maracanã,86.433333,2,1,0,4.3

In [84]:
# Dados fornecidos
dados = {
    'passeio': ['Cristo Redentor', 'Jardim Botânico', 'CCBB', 'Museu do Amanhã', 'Pão de Açúcar',
                'AquaRio', 'Theatro Municipal', 'Parque dos Patins', 'Mosteiro de São Bento',
                'Santa Teresa', 'Forte de Copacabana', 'BioParque do Rio', 'Maracanã'],
    'custo_passeio': [128.00, 23.00, 0.00, 30.00, 195.00, 120.00, 20.00, 30.00, 0.00, 20.00, 6.00, 51.60, 75.00],
    'tempo_passeio_min': [90, 105, 150, 90, 60, 90, 90, 50, 30, 120, 60, 150, 45],
    'interesse_passeio': [0.99, 0.8, 0.75, 0.85, 0.95, 0.7, 0.85, 0.8, 0.7, 0.9, 0.8, 0.7, 0.75],
    'score_passeio': [0.01, 0.20, 0.25, 0.15, 0.05, 0.30, 0.15, 0.20, 0.30, 0.10, 0.20, 0.30, 0.25]
}

# Criação do DataFrame
df_passeio = pd.DataFrame(dados)

# Exibição do DataFrame
df_passeio

,passeio,custo_passeio,tempo_passeio_min,interesse_passeio,score_passeio
0,Cristo Redentor,128.0,90,0.99,0.01
1,Jardim Botânico,23.0,105,0.80,0.20
2,CCBB,0.0,150,0.75,0.25
3,Museu do Amanhã,30.0,90,0.85,0.15
4,Pão de Açúcar,195.0,60,0.95,0.05
5,AquaRio,120.0,90,0.70,0.30
6,Theatro Municipal,20.0,90,0.85,0.15
7,Parque dos Patins,30.0,50,0.80,0.20
8,Mosteiro de São Bento,0.0,30,0.70,0.30
9,Santa Teresa,20.0,120,0.90,0.10
10,Forte de Copacabana,6.0,60,0.80,0.20
11,BioParque do Rio,51.6,150,0.70,0.30
12,Maracanã,75.0,45,0.75,0.25

In [85]:
df_caminhos.info()
print(df_caminhos['destino'].unique())
df_passeio.info()
print(df_passeio['passeio'].unique())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   origem              210 non-null    object
 1   destino             210 non-null    object
 2   total_duration_min  210 non-null    float64
 3   walking             210 non-null    int64
 4   bus                 210 non-null    int64
 5   subway              210 non-null    int64
 6   custo               210 non-null    float64
dtypes: float64(2), int64(3), object(2)
memory usage: 11.6+ KB
['Cristo Redentor' 'Jardim Botânico' 'CCBB' 'Museu do Amanhã'
 'Pão de Açúcar' 'AquaRio' 'Theatro Municipal' 'Parque dos Patins'
 'Mosteiro de São Bento' 'Santa Teresa' 'Forte de Copacabana'
 'BioParque do Rio' 'Maracanã' 'Restaurante Spesso' 'Hotel']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   passeio            13 non-null     object
 1   custo_passeio      13 non-null     float64
 2   tempo_passeio_min  13 non-null     int64
 3   interesse_passeio  13 non-null     float64
 4   score_passeio      13 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 652.0+ bytes
['Cristo Redentor' 'Jardim Botânico' 'CCBB' 'Museu do Amanhã'
 'Pão de Açúcar' 'AquaRio' 'Theatro Municipal' 'Parque dos Patins'
 'Mosteiro de São Bento' 'Santa Teresa' 'Forte de Copacabana'
 'BioParque do Rio' 'Maracanã']

In [86]:
# Fazer o merge entre os DataFrames df_caminhos e df_passeio
df_resultado = df_caminhos.merge(df_passeio, left_on='destino', right_on='passeio', how='left')

# Exibir o resultado
df_resultado

,origem,destino,total_duration_min,walking,bus,subway,custo,passeio,custo_passeio,tempo_passeio_min,interesse_passeio,score_passeio
0,Hotel,Cristo Redentor,79.016667,2,1,0,4.3,Cristo Redentor,128.0,90.0,0.99,0.01
1,Hotel,Jardim Botânico,48.083333,2,1,0,4.3,Jardim Botânico,23.0,105.0,0.80,0.20
2,Hotel,CCBB,19.683333,5,0,0,0.0,CCBB,0.0,150.0,0.75,0.25
3,Hotel,Museu do Amanhã,31.466667,1,0,0,0.0,Museu do Amanhã,30.0,90.0,0.85,0.15
4,Hotel,Pão de Açúcar,47.500000,2,0,1,7.5,Pão de Açúcar,195.0,60.0,0.95,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...
205,Restaurante Spesso,Mosteiro de São Bento,45.333333,2,1,0,4.3,Mosteiro de São Bento,0.0,30.0,0.70,0.30
206,Restaurante Spesso,Santa Teresa,44.166667,2,1,0,4.3,Santa Teresa,20.0,120.0,0.90,0.10
207,Restaurante Spesso,Forte de Copacabana,56.616667,2,1,0,4.3,Forte de Copacabana,6.0,60.0,0.80,0.20
208,Restaurante Spesso,BioParque do Rio,60.666667,3,2,0,8.6,BioParque do Rio,51.6,150.0,0.70,0.30
209,Restaurante Spesso,Maracanã,86.433333,2,1,0,4.3,Maracanã,75.0,45.0,0.75,0.25

In [87]:
df_resultado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   origem              210 non-null    object
 1   destino             210 non-null    object
 2   total_duration_min  210 non-null    float64
 3   walking             210 non-null    int64
 4   bus                 210 non-null    int64
 5   subway              210 non-null    int64
 6   custo               210 non-null    float64
 7   passeio             182 non-null    object
 8   custo_passeio       182 non-null    float64
 9   tempo_passeio_min   182 non-null    float64
 10  interesse_passeio   182 non-null    float64
 11  score_passeio       182 non-null    float64
dtypes: float64(6), int64(3), object(3)
memory usage: 19.8+ KB

In [96]:
df_resultado['custo_passeio'] = df_resultado['custo_passeio'].fillna(0)
df_resultado['tempo_passeio_min'] = df_resultado['tempo_passeio_min'].fillna(0)
df_resultado['interesse_passeio'] = df_resultado['interesse_passeio'].fillna(0)
df_resultado['score_passeio'] = df_resultado['score_passeio'].fillna(0)
df_resultado['passeio'] = df_resultado['passeio'].fillna('')  # Para colunas de texto, você pode substituir por uma string vazia

In [89]:
print(df_resultado.isnull().sum())

origem                0
destino               0
total_duration_min    0
walking               0
bus                   0
subway                0
custo                 0
passeio               0
custo_passeio         0
tempo_passeio_min     0
interesse_passeio     0
score_passeio         0
dtype: int64

In [97]:
df = df_resultado.drop(['walking', 'bus', 'subway', 'passeio', 'interesse_passeio'], axis=1)

# Exibir o DataFrame resultante
df

,origem,destino,total_duration_min,custo,custo_passeio,tempo_passeio_min,score_passeio
0,Hotel,Cristo Redentor,79.016667,4.3,128.0,90.0,0.01
1,Hotel,Jardim Botânico,48.083333,4.3,23.0,105.0,0.20
2,Hotel,CCBB,19.683333,0.0,0.0,150.0,0.25
3,Hotel,Museu do Amanhã,31.466667,0.0,30.0,90.0,0.15
4,Hotel,Pão de Açúcar,47.500000,7.5,195.0,60.0,0.05
...,...,...,...,...,...,...,...
205,Restaurante Spesso,Mosteiro de São Bento,45.333333,4.3,0.0,30.0,0.30
206,Restaurante Spesso,Santa Teresa,44.166667,4.3,20.0,120.0,0.10
207,Restaurante Spesso,Forte de Copacabana,56.616667,4.3,6.0,60.0,0.20
208,Restaurante Spesso,BioParque do Rio,60.666667,8.6,51.6,150.0,0.30
209,Restaurante Spesso,Maracanã,86.433333,4.3,75.0,45.0,0.25

In [98]:
# Verifique o tipo da coluna 'score_passeio'
print(df['score_passeio'].dtype)

float64

In [100]:
# Verificar se há registros com destino 'Restaurante Spesso'
df[df['destino'] == 'Restaurante Spesso']

,origem,destino,total_duration_min,custo,custo_passeio,tempo_passeio_min,score_passeio
13,Hotel,Restaurante Spesso,18.316667,7.5,0.0,0.0,0.0
27,Cristo Redentor,Restaurante Spesso,48.000000,0.0,0.0,0.0,0.0
41,Jardim Botânico,Restaurante Spesso,34.716667,4.3,0.0,0.0,0.0
55,CCBB,Restaurante Spesso,45.616667,4.3,0.0,0.0,0.0
69,Museu do Amanhã,Restaurante Spesso,59.150000,8.6,0.0,0.0,0.0
83,Pão de Açúcar,Restaurante Spesso,29.383333,0.0,0.0,0.0,0.0
97,AquaRio,Restaurante Spesso,47.000000,8.6,0.0,0.0,0.0
111,Theatro Municipal,Restaurante Spesso,20.000000,7.5,0.0,0.0,0.0
125,Parque dos Patins,Restaurante Spesso,48.750000,4.3,0.0,0.0,0.0
139,Mosteiro de São Bento,Restaurante Spesso,51.783333,4.3,0.0,0.0,0.0
153,Santa Teresa,Restaurante Spesso,22.300000,7.5,0.0,0.0,0.0
167,Forte de Copacabana,Restaurante Spesso,48.783333,4.3,0.0,0.0,0.0
181,BioParque do Rio,Restaurante Spesso,53.666667,8.6,0.0,0.0,0.0
195,Maracanã,Restaurante Spesso,74.066667,8.6,0.0,0.0,0.0

In [101]:
df.loc[df['destino'] == 'Restaurante Spesso', 'custo_passeio'] = 67.9

In [102]:
# Verificar se há registros com destino 'Restaurante Spesso'
df[df['destino'] == 'Restaurante Spesso']

,origem,destino,total_duration_min,custo,custo_passeio,tempo_passeio_min,score_passeio
13,Hotel,Restaurante Spesso,18.316667,7.5,67.9,0.0,0.0
27,Cristo Redentor,Restaurante Spesso,48.000000,0.0,67.9,0.0,0.0
41,Jardim Botânico,Restaurante Spesso,34.716667,4.3,67.9,0.0,0.0
55,CCBB,Restaurante Spesso,45.616667,4.3,67.9,0.0,0.0
69,Museu do Amanhã,Restaurante Spesso,59.150000,8.6,67.9,0.0,0.0
83,Pão de Açúcar,Restaurante Spesso,29.383333,0.0,67.9,0.0,0.0
97,AquaRio,Restaurante Spesso,47.000000,8.6,67.9,0.0,0.0
111,Theatro Municipal,Restaurante Spesso,20.000000,7.5,67.9,0.0,0.0
125,Parque dos Patins,Restaurante Spesso,48.750000,4.3,67.9,0.0,0.0
139,Mosteiro de São Bento,Restaurante Spesso,51.783333,4.3,67.9,0.0,0.0
153,Santa Teresa,Restaurante Spesso,22.300000,7.5,67.9,0.0,0.0
167,Forte de Copacabana,Restaurante Spesso,48.783333,4.3,67.9,0.0,0.0
181,BioParque do Rio,Restaurante Spesso,53.666667,8.6,67.9,0.0,0.0
195,Maracanã,Restaurante Spesso,74.066667,8.6,67.9,0.0,0.0

In [109]:
df.loc[df['destino'] == 'Restaurante Spesso', 'score_passeio'] = 0.1

In [110]:
# Verificar se há registros com destino 'Restaurante Spesso'
df[df['destino'] == 'Restaurante Spesso']

,origem,destino,total_duration_min,custo,custo_passeio,tempo_passeio_min,score_passeio
13,Hotel,Restaurante Spesso,18.316667,7.5,67.9,0.0,0.1
27,Cristo Redentor,Restaurante Spesso,48.000000,0.0,67.9,0.0,0.1
41,Jardim Botânico,Restaurante Spesso,34.716667,4.3,67.9,0.0,0.1
55,CCBB,Restaurante Spesso,45.616667,4.3,67.9,0.0,0.1
69,Museu do Amanhã,Restaurante Spesso,59.150000,8.6,67.9,0.0,0.1
83,Pão de Açúcar,Restaurante Spesso,29.383333,0.0,67.9,0.0,0.1
97,AquaRio,Restaurante Spesso,47.000000,8.6,67.9,0.0,0.1
111,Theatro Municipal,Restaurante Spesso,20.000000,7.5,67.9,0.0,0.1
125,Parque dos Patins,Restaurante Spesso,48.750000,4.3,67.9,0.0,0.1
139,Mosteiro de São Bento,Restaurante Spesso,51.783333,4.3,67.9,0.0,0.1
153,Santa Teresa,Restaurante Spesso,22.300000,7.5,67.9,0.0,0.1
167,Forte de Copacabana,Restaurante Spesso,48.783333,4.3,67.9,0.0,0.1
181,BioParque do Rio,Restaurante Spesso,53.666667,8.6,67.9,0.0,0.1
195,Maracanã,Restaurante Spesso,74.066667,8.6,67.9,0.0,0.1

In [93]:
# Atualizar a coluna 'custo_passeio' para 67.9 nas linhas onde o destino é 'Restaurante Spesso'
df.loc[df['destino'] == 'Restaurante Spesso', 'custo_passeio'] = 67.9

# Atualizar a coluna 'score_passeio' para 0.01 nas linhas onde o destino é 'Restaurante Spesso'
df.loc[df['destino'] == 'Restaurante Spesso', 'score_passeio'] = 0.01

In [94]:
df_restaurante_spesso = df[df['destino'] == 'Restaurante Spesso']
df_restaurante_spesso

,origem,destino,total_duration_min,custo,custo_passeio,tempo_passeio_min,score_passeio
13,Hotel,Restaurante Spesso,18.316667,7.5,67.9,0.0,0.01
27,Cristo Redentor,Restaurante Spesso,48.000000,0.0,67.9,0.0,0.01
41,Jardim Botânico,Restaurante Spesso,34.716667,4.3,67.9,0.0,0.01
55,CCBB,Restaurante Spesso,45.616667,4.3,67.9,0.0,0.01
69,Museu do Amanhã,Restaurante Spesso,59.150000,8.6,67.9,0.0,0.01
83,Pão de Açúcar,Restaurante Spesso,29.383333,0.0,67.9,0.0,0.01
97,AquaRio,Restaurante Spesso,47.000000,8.6,67.9,0.0,0.01
111,Theatro Municipal,Restaurante Spesso,20.000000,7.5,67.9,0.0,0.01
125,Parque dos Patins,Restaurante Spesso,48.750000,4.3,67.9,0.0,0.01
139,Mosteiro de São Bento,Restaurante Spesso,51.783333,4.3,67.9,0.0,0.01
153,Santa Teresa,Restaurante Spesso,22.300000,7.5,67.9,0.0,0.01
167,Forte de Copacabana,Restaurante Spesso,48.783333,4.3,67.9,0.0,0.01
181,BioParque do Rio,Restaurante Spesso,53.666667,8.6,67.9,0.0,0.01
195,Maracanã,Restaurante Spesso,74.066667,8.6,67.9,0.0,0.01

In [111]:
df.sample(10)

,origem,destino,total_duration_min,custo,custo_passeio,tempo_passeio_min,score_passeio
199,Restaurante Spesso,CCBB,37.016667,4.3,0.0,150.0,0.25
133,Mosteiro de São Bento,Theatro Municipal,19.916667,0.0,20.0,90.0,0.15
127,Mosteiro de São Bento,Cristo Redentor,86.166667,4.3,128.0,90.0,0.01
153,Santa Teresa,Restaurante Spesso,22.300000,7.5,67.9,0.0,0.10
85,AquaRio,Cristo Redentor,91.633333,8.6,128.0,90.0,0.01
189,Maracanã,Theatro Municipal,62.783333,8.6,20.0,90.0,0.15
61,Museu do Amanhã,AquaRio,18.183333,0.0,120.0,90.0,0.30
79,Pão de Açúcar,Santa Teresa,66.000000,4.3,20.0,120.0,0.10
182,Maracanã,Hotel,66.016667,8.6,0.0,0.0,0.00
144,Santa Teresa,Museu do Amanhã,30.083333,0.0,30.0,90.0,0.15

In [ ]:
df.to_csv('../data/rawDataGmaps.csv', index=False)