In [25]:
import pandas as pd

In [ ]:
df = pd.read_csv('../data/rawDataGmaps.csv')

# Exibir as primeiras linhas do DataFrame para garantir que foi carregado corretamente
df.head()

,origem,destino,total_duration_min,custo,custo_passeio,tempo_passeio_min,score_passeio
0,Hotel,Cristo Redentor,79.016667,4.3,128.0,90.0,0.01
1,Hotel,Jardim Botânico,48.083333,4.3,23.0,105.0,0.20
2,Hotel,CCBB,19.683333,0.0,0.0,150.0,0.25
3,Hotel,Museu do Amanhã,31.466667,0.0,30.0,90.0,0.15
4,Hotel,Pão de Açúcar,47.500000,7.5,195.0,60.0,0.05

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   origem              210 non-null    object
 1   destino             210 non-null    object
 2   total_duration_min  210 non-null    float64
 3   custo               210 non-null    float64
 4   custo_passeio       210 non-null    float64
 5   tempo_passeio_min   210 non-null    float64
 6   score_passeio       210 non-null    float64
dtypes: float64(5), object(2)
memory usage: 11.6+ KB

In [28]:
df.describe()

,total_duration_min,custo,custo_passeio,tempo_passeio_min,score_passeio
count,210.000000,210.000000,210.000000,210.000000,210.000000
mean,60.894365,4.760000,51.100000,75.333333,0.170667
std,30.915372,3.132561,55.330822,45.069148,0.098789
min,3.616667,0.000000,0.000000,0.000000,0.000000
25%,37.079167,4.300000,6.000000,45.000000,0.100000
50%,60.858333,4.300000,30.000000,90.000000,0.200000
75%,83.845833,8.600000,75.000000,105.000000,0.250000
max,149.150000,12.900000,195.000000,150.000000,0.300000

In [29]:
df.describe(include='object')

       origem          destino
count     210              210
unique     15               15
top     Hotel  Cristo Redentor
freq       14               14

In [30]:
df_restaurante_spesso = df[df['destino'] == 'Restaurante Spesso']
df_restaurante_spesso

,origem,destino,total_duration_min,custo,custo_passeio,tempo_passeio_min,score_passeio
13,Hotel,Restaurante Spesso,18.316667,7.5,67.9,0.0,0.1
27,Cristo Redentor,Restaurante Spesso,48.000000,0.0,67.9,0.0,0.1
41,Jardim Botânico,Restaurante Spesso,34.716667,4.3,67.9,0.0,0.1
55,CCBB,Restaurante Spesso,45.616667,4.3,67.9,0.0,0.1
69,Museu do Amanhã,Restaurante Spesso,59.150000,8.6,67.9,0.0,0.1
83,Pão de Açúcar,Restaurante Spesso,29.383333,0.0,67.9,0.0,0.1
97,AquaRio,Restaurante Spesso,47.000000,8.6,67.9,0.0,0.1
111,Theatro Municipal,Restaurante Spesso,20.000000,7.5,67.9,0.0,0.1
125,Parque dos Patins,Restaurante Spesso,48.750000,4.3,67.9,0.0,0.1
139,Mosteiro de São Bento,Restaurante Spesso,51.783333,4.3,67.9,0.0,0.1
153,Santa Teresa,Restaurante Spesso,22.300000,7.5,67.9,0.0,0.1
167,Forte de Copacabana,Restaurante Spesso,48.783333,4.3,67.9,0.0,0.1
181,BioParque do Rio,Restaurante Spesso,53.666667,8.6,67.9,0.0,0.1
195,Maracanã,Restaurante Spesso,74.066667,8.6,67.9,0.0,0.1

In [31]:
# Criando a coluna 'custo_total' como a soma de 'custo' e 'custo_passeio'
df['custo_total'] = df['custo'] + df['custo_passeio']

# Criando a coluna 'tempo_total' como a soma de 'total_duration_min' e 'tempo_passeio_min'
df['tempo_total'] = df['total_duration_min'] + df['tempo_passeio_min']

# Exibindo o DataFrame atualizado
df

,origem,destino,total_duration_min,custo,custo_passeio,tempo_passeio_min,score_passeio,custo_total,tempo_total
0,Hotel,Cristo Redentor,79.016667,4.3,128.0,90.0,0.01,132.3,169.016667
1,Hotel,Jardim Botânico,48.083333,4.3,23.0,105.0,0.20,27.3,153.083333
2,Hotel,CCBB,19.683333,0.0,0.0,150.0,0.25,0.0,169.683333
3,Hotel,Museu do Amanhã,31.466667,0.0,30.0,90.0,0.15,30.0,121.466667
4,Hotel,Pão de Açúcar,47.500000,7.5,195.0,60.0,0.05,202.5,107.500000
...,...,...,...,...,...,...,...,...,...
205,Restaurante Spesso,Mosteiro de São Bento,45.333333,4.3,0.0,30.0,0.30,4.3,75.333333
206,Restaurante Spesso,Santa Teresa,44.166667,4.3,20.0,120.0,0.10,24.3,164.166667
207,Restaurante Spesso,Forte de Copacabana,56.616667,4.3,6.0,60.0,0.20,10.3,116.616667
208,Restaurante Spesso,BioParque do Rio,60.666667,8.6,51.6,150.0,0.30,60.2,210.666667
209,Restaurante Spesso,Maracanã,86.433333,4.3,75.0,45.0,0.25,79.3,131.433333

In [34]:
df.sample(10, random_state=1)

,origem,destino,total_duration_min,custo,custo_passeio,tempo_passeio_min,score_passeio,custo_total,tempo_total
44,CCBB,Jardim Botânico,55.616667,4.3,23.0,105.0,0.20,27.3,160.616667
188,Maracanã,AquaRio,75.150000,8.6,120.0,90.0,0.30,128.6,165.150000
51,CCBB,Santa Teresa,18.833333,0.0,20.0,120.0,0.10,20.0,138.833333
204,Restaurante Spesso,Parque dos Patins,45.366667,4.3,30.0,50.0,0.20,34.3,95.366667
35,Jardim Botânico,Parque dos Patins,23.100000,0.0,30.0,50.0,0.20,30.0,73.100000
89,AquaRio,Pão de Açúcar,91.400000,8.6,195.0,60.0,0.05,203.6,151.400000
33,Jardim Botânico,AquaRio,70.200000,8.6,120.0,90.0,0.30,128.6,160.200000
167,Forte de Copacabana,Restaurante Spesso,48.783333,4.3,67.9,0.0,0.10,72.2,48.783333
205,Restaurante Spesso,Mosteiro de São Bento,45.333333,4.3,0.0,30.0,0.30,4.3,75.333333
168,BioParque do Rio,Hotel,50.850000,4.3,0.0,0.0,0.00,4.3,50.850000

In [35]:
df_tour = df.drop(['total_duration_min', 'tempo_passeio_min', 'custo', 'custo_passeio'], axis=1)
df_tour

,origem,destino,score_passeio,custo_total,tempo_total
0,Hotel,Cristo Redentor,0.01,132.3,169.016667
1,Hotel,Jardim Botânico,0.20,27.3,153.083333
2,Hotel,CCBB,0.25,0.0,169.683333
3,Hotel,Museu do Amanhã,0.15,30.0,121.466667
4,Hotel,Pão de Açúcar,0.05,202.5,107.500000
...,...,...,...,...,...
205,Restaurante Spesso,Mosteiro de São Bento,0.30,4.3,75.333333
206,Restaurante Spesso,Santa Teresa,0.10,24.3,164.166667
207,Restaurante Spesso,Forte de Copacabana,0.20,10.3,116.616667
208,Restaurante Spesso,BioParque do Rio,0.30,60.2,210.666667
209,Restaurante Spesso,Maracanã,0.25,79.3,131.433333

In [36]:
df_tour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   origem         210 non-null    object
 1   destino        210 non-null    object
 2   score_passeio  210 non-null    float64
 3   custo_total    210 non-null    float64
 4   tempo_total    210 non-null    float64
dtypes: float64(3), object(2)
memory usage: 8.3+ KB

In [ ]:
df_tour.to_csv('../data/data.csv', index=False)